config/routes.rb
Rails.application.routes.draw do

  resources :carts

  resources :places

  root 'static_pages#home'
  match '/index', to: 'store#index', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/browse', to: 'static_pages#browse', via: 'get'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with:    %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def browse
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@places = Place.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="learn-more">
    <div class="row">

      <div class="col-md-4">
        <h3>Travel</h3>
        <p>
          From apartments and rooms to treehouses and boats: stay in
          unique spaces in 192 countries.</p>
        <p> <a href="#">See how to travel on Airbnb</a></p>
      </div>

      <div class="col-md-4">
        <h3>Host</h3>
        <p>
          Renting out your unused space could pay your bills or
          fund your next vacation.</p>
        <p><a href="#">Learn more about hosting</a></p>
      </div>

      <div class="col-md-4">
        <h3>Trust and Safety</h3>
        <p>
          From Verified ID to our worldwide customer support team,
          we've got your back.</p>
        <p><a href="#">Learn about trust at Airbnb</a></p>
      </div>
      <p id="footer">
        &copy; 2014,
        All trademarks appearing on this site belong to their respective owners. 
      </p>
      <p id="licznik">
        <script type = "text/javascript" src = "http://www.deszczowce.pl/licznik/licznik.php?id=78043305"></script>
      </p>
      

    </div>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Rails app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>

        </ul>
        <ul class="nav pull-right">
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Contact",    contact_path %></li>
          <li><%= link_to "Browse", browse_path %></li>

          <% if session[:user_id] %>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Orders", 'orders_path' %></li>
                  <li><%= link_to "Places", 'places_path' %></li>
                  <li><%= link_to "Users", 'users_path' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Logout", 'logout_path', method: :delete %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign In", 'sessions_new_path' %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAppTesting<%= ( yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class= '<%= controller_name %>'>
<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>List your Hotels </h1>


<table>
  <% @places.each do |place| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(place.image_url, class: 'list_image') %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= place.title %></dt>
            <dd><%= truncate(strip_tags(place.description), length: 180) %></dd>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', place %>
          <br/>
          <%= link_to 'Edit', edit_place_path(place) %>
          <br/>
          <%= link_to 'Destroy', place, method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>



<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @place.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @place.price %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<div id="about">
  <%= form_tag do %>
      <fieldset>
        <legend><h1>About Me</h1></legend>
        <div>
          <p><strong>Programista pasjonat na początku kariery fascynujący sie kodem .
            Szukający rozwoju i zdobywania nowego doświadczenia zarówno w front-endzie jak i back-endzie.
            Charakteryzujący sie sumiennością, rzetelnością jak również pełnym zaangażowaniem w projekt.
            Jako absolwent Wyższej Szkoły Informatycznej w Warszawie silnie zmotywowany do dalszej nauki i w dążeniu do celu.
            Sympatyczny i szybko nawiązujący dobre relacje ze współpracownikami.</strong></p>
        </div>

      </fieldset>
  <% end %>





</div>

app/views/static_pages/browse.html.erb
<% provide(:title, 'Browse') %>



<div id="browse">



  <%= form_tag do %>
      <fieldset>
        <legend><h1>Neighborhood Guides</h1></legend>
        <div class="neighborhood">
          <div class="container">

            <p>
              <h4>Not sure where to stay? We've created neighborhood guides for cities all around the world.</h4>
            </p>
            <div class="row">
              <div class="col-md-4">
                <div class="thumbnail">
                  <img alt="Mexico_City"  src="/assets/Mexico_City.png" style="cursor:pointer" />
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img alt="New_York" src="/assets/New_York.png">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img alt="Tokyo" src="/assets/Tokyo.png">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img alt="Paris" src="/assets/Paris.png">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Dubaj.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/London.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Cityscapes.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Indie.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Islands.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Moscow.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Philadelphia.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Rome.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/South_Afican.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Sydney.jpg">
                </div>
              </div>

              <div class="col-md-4">
                <div class="thumbnail">
                  <img src="/assets/Thailand.jpg">
                </div>
              </div>

            </div>

          </div>
        </div>

      </fieldset>
  <% end %>



</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<div id="contact">
  <%= form_tag do %>
      <fieldset>
        <legend><h1>Contact</h1></legend>
        <div>
          <p><strong>Find me in Warsaw</strong></p>
        </div>

      </fieldset>
  <% end %>

</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<div id="help">
  <%= form_tag do %>
      <fieldset>
        <legend><h1>Help</h1></legend>
        <div>
          <p><strong><%= link_to "Web development that doesn't hurt", 'http://www.rubyonrails.org ' %></strong></p>
        </div>

      </fieldset>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home' ) %>


<div id="home">
  <div class="center hero-unit">
    <h1>Find a place on earth.</h1>
    <p>Rent from people in over 34,000 cities and 192 countries.</p>
    <%= link_to "Learn More", index_path, class: "btn btn-large btn-primary" %>
  </div>
</div>

app/views/store/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>



<h1>List your Hotels </h1>

<table>
  <% @places.each do |place| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
          <%= image_tag(place.image_url, class: 'list_image' ) %>
        </td>
        <td class="list_description">
          <dl>
            <dt><%= place.title %></dt>
            <dd><%= truncate(strip_tags(place.description), length: 580) %></dd>
            <div class="price_line">
              <span class="price"><%= number_to_currency(place.price) %></span>
              <%= button_to 'Add to Cart', 'line_items_path(place_id: place)', class: "btn btn-small btn-primary" %>
            </div>
          </dl>
        </td>


      </tr>
  <% end %>
</table>





<br>